import Head from "next/head";

export const Header = () => {
  return (
  <Head>
    <title>Tribute</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <link rel="iconarrow" href="/downarrow.png" />
  </Head>
  );
};

export default Header;